production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci 
  reconnect: false
  database: weixin_test
  pool: 5
  timeout: 5000
  username: root
  password: free
  socket: /var/run/mysqld/mysqld.sock